CREATE TABLE "transacoes" (
	"id"	INTEGER NOT NULL,
	"valor"	REAL NOT NULL,
	"data"	NUMERIC NOT NULL,
	"hora"	NUMERIC NOT NULL,
	"dia_semana"	TEXT NOT NULL,
	"categoria"	TEXT NOT NULL,
	"conta"	TEXT NOT NULL,
	"cidade"	TEXT NOT NULL,
	"estado"	TEXT NOT NULL,
	"pais"	TEXT NOT NULL,
	"latitude"	TEXT NOT NULL,
	"longitude"	TEXT NOT NULL,
	"tipo_transacao"	TEXT NOT NULL,
	"dispositivo"	TEXT NOT NULL,
	"estabelecimento"	TEXT NOT NULL,
	"tentativas"	INTEGER NOT NULL,
	"ip_origem"	TEXT NOT NULL,
	"is_fraude"	NUMERIC NOT NULL,
	PRIMARY KEY("id")
)